### PR TITLE
a couple typo fixes

### PR DESCRIPTION
**Pull request by apjanke**
Just a couple suggested typo fixes in the README.

### CODE REVIEW

**Comment by sffc** [comment]
> [CLA assistant check](https://cla-assistant.io/octave-online/octave-online-server?pullRequest=15)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/octave-online/octave-online-server?pullRequest=15) before we can accept your contribution.
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/octave-online/octave-online-server?pullRequest=15) it.

Ignore this for the time being; I was experimenting with a CLA setup, but the CLA still says "SAP" on it.

Are you okay if the contributed code passes through a CLA (giving Octave Online LLC the right to sublicense the code), or would that deter contributions for you?

**Comment by sffc** [comment]
@apjanke - The CLA is ready to go. You can read more information here:

https://github.com/octave-online/octave-online-server#contributing

Please use the link from @CLAassistant to complete the CLA. Thank you!

**Comment by apjanke** [comment]
Done!

**Comment by sffc** [comment]
Merged! (the CI failure above is fixed on the master branch now)

**Pull request merged**
